### ISSUE TITLE
OS in Issue Template

### ISSUE THREAD

**Issue by rchtgpt** [MLH-Fellowship/soochit#24]
## Summary

The current issue template asks the contributors to tell the android device and its version. however, since we're working on flutter and have ios as well, we need to have put a generic term "OS" instead of "android."

## Screenshots
![image](https://user-images.githubusercontent.com/44428198/94483628-cbf0b880-01f8-11eb-82f6-ab594b994da9.png)

**Comment by Starlight220** [comment]
I'll do this soon!

**Comment by sheldor1510** [comment]
Hey, can I take up this issue?

**Comment by rchtgpt** [comment]
> Hey, can I take up this issue?

@sheldor1510, @Starlight220 hasn't created a PR yet so yeah you can go ahead with it! 😃
