### ISSUE TITLE
Specific Home Screen Redirect after Role Selection

### ISSUE THREAD

**Issue by rchtgpt** [MLH-Fellowship/soochit#25]
## Summary

After the user selects their role as a patient or as a doctor, they should be redirected to their respective home screens.

patients should be redirected to `HomePatients()` and the doctors should be redirected to `HomeDoctor()`

## Observed behaviour

Currently, the icon on the welcome screen (i.e. the role selection screen) doesn't do anything.

**Comment by Imperial-lord** [comment]
Have made all the preferred changes and integrated all the pages. Take a look at the PR and see if it should be merged.
